# This file intentionally left blank
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes

